name: Kodular
title: Kodular
description: Drag and Drop Android App Creator. No coding required!

social:
  twitter: https://twitter.com/KodularIO
  fb: https://www.facebook.com/Kodular
  github: https://github.com/Kodular
  discord: https://kodul.ar/discord
  telegram: https://telegram.me/Kodular
  instagram: https://instagram.com/Kodular

plugins:
  - jekyll-redirect-from
  - jekyll-sitemap
  
